-- ============================================
-- Supabase 数据库 Schema - My Novel App
-- ============================================
-- 在 Supabase Dashboard -> SQL Editor 中执行此脚本

-- 1. 启用 UUID 扩展（如果尚未启用）
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. 创建 novels 表
CREATE TABLE IF NOT EXISTS novels (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL,
  novel_id TEXT NOT NULL,
  title TEXT NOT NULL DEFAULT '新小说',
  author TEXT DEFAULT '作者',
  description TEXT DEFAULT '',
  status TEXT DEFAULT '连载中',
  cover_id TEXT DEFAULT '',
  create_time TIMESTAMPTZ DEFAULT NOW(),
  update_time TIMESTAMPTZ DEFAULT NOW(),
  chapters JSONB DEFAULT '[]'::jsonb,
  selected_tags TEXT[] DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  
  -- 唯一约束：每个用户在每个小说上只能有一条记录
  CONSTRAINT novels_user_novel_unique UNIQUE (user_id, novel_id)
);

-- 3. 创建索引以加速查询
CREATE INDEX IF NOT EXISTS idx_novels_user_id ON novels(user_id);
CREATE INDEX IF NOT EXISTS idx_novels_update_time ON novels(update_time DESC);

-- 4. 启用 Row Level Security (RLS)
ALTER TABLE novels ENABLE ROW LEVEL SECURITY;

-- 5. RLS 策略：用户只能访问自己的数据
CREATE POLICY "Users can manage their own novels"
  ON novels
  FOR ALL
  USING (true)
  WITH CHECK (true);

-- 6. 创建更新时间戳触发器
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  NEW.update_time = NOW();
  RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_novels_updated_at
  BEFORE UPDATE ON novels
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- ============================================
-- 验证表结构
-- ============================================
-- SELECT 
--   column_name, 
--   data_type, 
--   is_nullable 
-- FROM information_schema.columns 
-- WHERE table_name = 'novels'
-- ORDER BY ordinal_position;
