-- ============================================
-- 用户认证系统 - Profiles 表
-- ============================================
-- 启用 UUID 扩展（如果尚未启用）
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Profiles 表：存储用户额外信息
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  email TEXT,
  full_name TEXT,
  avatar_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 允许用户注册时自动创建 profile
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- 策略：用户只能查看和更新自己的 profile
CREATE POLICY "Users can view own profile"
  ON public.profiles FOR SELECT
  USING (auth.uid() = id);

CREATE POLICY "Users can update own profile"
  ON public.profiles FOR UPDATE
  USING (auth.uid() = id);

-- 策略：注册时允许插入自己的 profile
CREATE POLICY "Users can insert own profile"
  ON public.profiles FOR INSERT
  WITH CHECK (auth.uid() = id);

-- 创建 profile 的自动触发器（用户注册时自动创建）
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name, avatar_url)
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'full_name', NEW.raw_user_meta_data->>'name'),
    NEW.raw_user_meta_data->>'avatar_url'
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 触发器：在用户创建时自动创建 profile
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ============================================
-- 小说系统表
-- ============================================
-- 1. 启用 UUID 扩展（如果尚未启用）
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. 创建 novels 表
CREATE TABLE IF NOT EXISTS novels (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  novel_id TEXT NOT NULL,
  title TEXT NOT NULL DEFAULT '新小说',
  author TEXT DEFAULT '作者',
  description TEXT DEFAULT '',
  status TEXT DEFAULT '连载中',
  cover_id TEXT DEFAULT '',
  create_time TIMESTAMPTZ DEFAULT NOW(),
  update_time TIMESTAMPTZ DEFAULT NOW(),
  chapters JSONB DEFAULT '[]'::jsonb,
  selected_tags TEXT[] DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),

  -- 唯一约束：每个用户在每个小说上只能有一条记录
  CONSTRAINT novels_user_novel_unique UNIQUE (user_id, novel_id)
);

-- 3. 创建索引以加速查询
CREATE INDEX IF NOT EXISTS idx_novels_user_id ON novels(user_id);
CREATE INDEX IF NOT EXISTS idx_novels_update_time ON novels(update_time DESC);

-- 4. 启用 Row Level Security (RLS)
ALTER TABLE novels ENABLE ROW LEVEL SECURITY;

-- 5. RLS 策略：用户只能访问自己的小说数据
-- 注意：数据库中 user_id 为 UUID 类型，直接与 auth.uid() (UUID) 比较

-- 查看自己的小说
DROP POLICY IF EXISTS "Users can view own novels" ON novels;
CREATE POLICY "Users can view own novels"
  ON novels FOR SELECT
  USING (auth.uid() = user_id);

-- 创建自己的小说
DROP POLICY IF EXISTS "Users can insert own novels" ON novels;
CREATE POLICY "Users can insert own novels"
  ON novels FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- 更新自己的小说
DROP POLICY IF EXISTS "Users can update own novels" ON novels;
CREATE POLICY "Users can update own novels"
  ON novels FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- 删除自己的小说
DROP POLICY IF EXISTS "Users can delete own novels" ON novels;
CREATE POLICY "Users can delete own novels"
  ON novels FOR DELETE
  USING (auth.uid() = user_id);

-- 6. 创建更新时间戳触发器
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  NEW.update_time = NOW();
  RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_novels_updated_at
  BEFORE UPDATE ON novels
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- ============================================
-- 验证表结构
-- ============================================
-- SELECT 
--   column_name, 
--   data_type, 
--   is_nullable 
-- FROM information_schema.columns 
-- WHERE table_name = 'novels'
-- ORDER BY ordinal_position;
